import tireimage from "../china-tyre-1000x1000-removebg-preview.png";

const Dummy_tires = [
  {
    key: "id",
    id: "ti1",
    name: "Rubber China Car Tyre",
    Size: "145/80 R12",
    tyre_type: "Radical",
    Rim_Diam: "12 inch",
    vehicle: "car",
    price: "40000",
    image: tireimage,
  },
  {
    key: "id",
    id: "ti2",
    name: "suzuki china",
    Size: "20 -60 R 16",
    image: tireimage,
    tyre_type: "Radical",
    Rim_Diam: " 16 Inch",
    vehicle: "car",
    price: "10000",
  },
  {
    key: "id",
    id: "ti3",
    image: tireimage,
    name: "Toyota new tire",
    Size: "20 -60 R 16",
    tyre_type: "Radical",
    Rim_Diam: " 16 Inch",
    vehicle: "car",
    price: "23530",
  },
  {
    key: "id",
    id: "ti4",
    image: tireimage,
    name: "radical tire ",
    Size: "20 -60 R 16",
    tyre_type: "Radical",
    Rim_Diam: " 16 Inch",
    vehicle: "car",
    price: "17300",
  },
  {
    key: "id",
    id: "ti5",
    image: tireimage,
    name: "GoodDay Brand",
    Size: "20 -60 R 16",
    tyre_type: "Radical",
    Rim_Diam: " 16 Inch",
    vehicle: "car",
    price: "15600",
  },
  {
    key: "id",
    id: "ti6",
    image: tireimage,
    name: "xmas pro tire",
    Size: "20 -60 R 16",
    tyre_type: "Radical",
    Rim_Diam: " 16 Inch",
    vehicle: "car",
    price: "12500",
  },
];

export default Dummy_tires;
